blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities
    about: Please do not disclose vulnerabilities in public issues.
